services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "44044:44044"
    command: /main
    restart: always
  db:
    restart: always
    image: postgres:latest
    ports:
      - "5440:5432"
    environment:
      - POSTGRES_DB=exchanger
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6390:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning

volumes:
  app:
  db:
  redis_data:
