env: "production"

database:
  host: db
  port: "5432"
  user: "postgres"
  dbname: "exchanger"
  max_attempts: 10

redis:
  host: "redis"
  port: "6379"
  password: ""
  dbnumber: 0

domain: "localhost"

grpc:
  port: "44044"
  timeout: 360s
